# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{routengn}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Keith Larrimore", "Quin Hoxie"]
  s.date = %q{2009-09-30}
  s.default_executable = %q{ngncmd}
  s.description = %q{RouteNGN is an Advanced SIP Redirect Routing Platform.}
  s.email = %q{keithlarrimore+github@gmail.com}
  s.executables = ["ngncmd"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "bin/ngncmd",
     "docs/RouteNGN-Gems-Install.doc",
     "examples/provision.rb",
     "lib/routengn.rb",
     "lib/routengn/console.rb",
     "lib/routengn/http/multipart.rb",
     "lib/routengn/mapper.rb",
     "lib/routengn/models/carrier.rb",
     "lib/routengn/models/dialcode.rb",
     "lib/routengn/models/endpoint.rb",
     "lib/routengn/models/group.rb",
     "lib/routengn/models/instance.rb",
     "lib/routengn/models/locale.rb",
     "lib/routengn/models/rate.rb",
     "lib/routengn/models/record.rb",
     "lib/routengn/models/region.rb",
     "lib/routengn/models/routecase.rb",
     "lib/routengn/models/type.rb",
     "lib/routengn/uploader.rb",
     "routengn.gemspec",
     "script/console"
  ]
  s.homepage = %q{http://github.com/klarrimore/routengn}
  s.rdoc_options = ["--inline-source", "--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{RouteNGN is an Advanced SIP Redirect Routing Platform.}
  s.test_files = [
    "examples/provision.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end
