#!/usr/bin/env ruby

irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'


exec "#{irb} -I \"#{File.dirname(__FILE__)}/../lib\" -r \"routengn\" -I \"#{File.dirname(__FILE__)}/../lib/routengn\" -r \"console\" --simple-prompt"
